/**
 * Allowlist de autenticação: só os paths listados aqui exigem token Firebase.
 *
 * Vive fora de `app.ts` para poder ser testada sem subir o registry inteiro de
 * rotas — toda rota nova que lê ou escreve dado de usuário precisa entrar aqui.
 */

/** Paths que exigem autenticação Firebase. */
export const AUTH_REQUIRED_PATHS: (string | RegExp)[] = [
  "/api/chat",
  "/api/chat-stream",
  "/api/simcar/clip/import-vectorized",
  "/api/simcar/clip/analyze",
  "/api/simcar/clip/analyze-auas",
  "/api/simcar/clip/analyze-auas-pos2008",
  "/api/simcar/clip/analyze-ac-vegetacao",
  "/api/simcar/imagery/catalog",
  // Estado das 3 fases da análise pós-recorte (lê o laudo persistido do job).
  /^\/api\/simcar\/clip\/phases\/[^/]+$/,
  "/api/simcar/clip/analyze/chat",
  "/api/simcar/clip/report",
  "/api/simcar/clip/report-docx",
  // DELETE de um job de recorte: apaga arquivos a partir de URLs do corpo.
  /^\/api\/simcar\/clip\/[^/]+$/,
  // Download do ZIP de um job de recorte (2 segmentos — a regex acima não cobre).
  /^\/api\/simcar\/clip\/download\/[^/]+$/,
  "/api/simcar/receipts/search",
  /^\/api\/simcar\/receipts\/download\/[^/]+$/,
  "/api/cbers-wpm/search",
  "/api/cbers-wpm/estimate",
  "/api/cbers-wpm/jobs",
  /^\/api\/cbers-wpm\/jobs\/[^/]+\/status$/,
  /^\/api\/cbers-wpm\/jobs\/[^/]+\/events$/,
  /^\/api\/cbers-wpm\/jobs\/[^/]+$/,
  "/api/landsat/search",
  "/api/landsat/estimate",
  "/api/landsat/jobs",
  /^\/api\/landsat\/jobs\/[^/]+\/status$/,
  /^\/api\/landsat\/jobs\/[^/]+\/events$/,
  /^\/api\/landsat\/jobs\/[^/]+$/,
  "/api/simcar/clip/analyze-ndvi",
  /^\/api\/simcar\/clip\/ndvi\/[^/]+$/,
  /^\/api\/simcar\/clip\/ndvi\/[^/]+\/events$/,
  "/api/ndvi/archive",
  // Aba NDVI dedicada (cena completa, padrão CBERS) — backend/ndvi-scene/.
  "/api/ndvi/search",
  "/api/ndvi/jobs",
  /^\/api\/ndvi\/jobs\/[^/]+\/status$/,
  /^\/api\/ndvi\/jobs\/[^/]+\/events$/,
  /^\/api\/ndvi\/jobs\/[^/]+$/,
  "/api/vertices/upload",
  "/api/vertices/process",
  /^\/api\/vertices\/jobs\/[^/]+\/status$/,
  /^\/api\/vertices\/jobs\/[^/]+\/events$/,
  /^\/api\/vertices\/jobs\/[^/]+$/,
  /^\/api\/vertices\/download\/[^/]+$/,
  "/api/containment/upload",
  "/api/containment/process",
  /^\/api\/containment\/jobs\/[^/]+\/status$/,
  /^\/api\/containment\/jobs\/[^/]+\/events$/,
  /^\/api\/containment\/download\/[^/]+$/,
  /^\/api\/containment\/jobs\/[^/]+$/,
  "/api/overlap/upload",
  "/api/overlap/process",
  "/api/overlap/sources/health",
  /^\/api\/overlap\/jobs\/[^/]+\/status$/,
  /^\/api\/overlap\/jobs\/[^/]+\/events$/,
  /^\/api\/overlap\/download\/[^/]+$/,
  /^\/api\/overlap\/jobs\/[^/]+$/,
  "/api/croqui/upload",
  "/api/croqui/route-options",
  "/api/croqui/process",
  /^\/api\/croqui\/jobs\/[^/]+\/status$/,
  /^\/api\/croqui\/jobs\/[^/]+\/events$/,
  /^\/api\/croqui\/download\/[^/]+$/,
  /^\/api\/croqui\/jobs\/[^/]+$/,
  "/api/croqui/uploads",
  "/api/fiscalizacao/sources",
  "/api/fiscalizacao/upload",
  "/api/fiscalizacao/process",
  /^\/api\/fiscalizacao\/jobs\/[^/]+\/status$/,
  /^\/api\/fiscalizacao\/jobs\/[^/]+\/events$/,
  /^\/api\/fiscalizacao\/download\/[^/]+$/,
  /^\/api\/fiscalizacao\/jobs\/[^/]+$/,
  "/api/geometry-errors/upload",
  "/api/geometry-errors/process",
  /^\/api\/geometry-errors\/jobs\/[^/]+\/status$/,
  /^\/api\/geometry-errors\/jobs\/[^/]+\/events$/,
  /^\/api\/geometry-errors\/download\/[^/]+$/,
  /^\/api\/geometry-errors\/jobs\/[^/]+$/,
  "/api/processar-projeto/upload",
  "/api/processar-projeto/importar",
  "/api/processar-projeto/processar",
  /^\/api\/processar-projeto\/import\/[^/]+\/pdf$/,
  /^\/api\/processar-projeto\/jobs\/[^/]+\/status$/,
  /^\/api\/processar-projeto\/jobs\/[^/]+\/events$/,
  /^\/api\/processar-projeto\/download\/[^/]+$/,
  /^\/api\/processar-projeto\/jobs\/[^/]+$/,
  "/api/simcar-oraculo/health",
  "/api/simcar-oraculo/test-project",
  "/api/simcar-oraculo/municipios",
  "/api/simcar-oraculo/pipeline",
  "/api/simcar-oraculo/importar",
  "/api/simcar-oraculo/processar",
  "/api/simcar-oraculo/shape-preview",
  /^\/api\/simcar-oraculo\/jobs\/[^/]+$/,
  /^\/api\/simcar-oraculo\/jobs\/[^/]+\/events$/,
  /^\/api\/simcar-oraculo\/jobs\/[^/]+\/artifact\/[^/]+$/,
  /^\/api\/simcar-oraculo\/jobs\/[^/]+\/autofix$/,
  /^\/api\/simcar-oraculo\/jobs\/[^/]+\/pdf-import$/,
  /^\/api\/simcar-oraculo\/jobs\/[^/]+\/pdf-process$/,
  /^\/api\/simcar-oraculo\/jobs\/[^/]+\/erros-zip$/,
  "/api/simcar-lotes/monitor-status",
  "/api/simcar-lotes/parse-recibos",
  "/api/simcar-lotes/process",
  /^\/api\/simcar-lotes\/jobs\/[^/]+\/(status|events)$/,
  /^\/api\/simcar-lotes\/jobs\/[^/]+$/,
  /^\/api\/simcar-lotes\/download\/[^/]+$/,
  "/api/auas-sccon/process",
  /^\/api\/auas-sccon\/download\/[^/]+$/,
  "/api/process/cancel",
  "/api/account/bootstrap",
  "/api/me",
  "/api/store/doc",
  "/api/store/collection",
  "/api/billing/me",
  "/api/billing/topups/manual",
  "/api/billing/ledger",
  "/api/solicitacao-prioridade/process",
  /^\/api\/solicitacao-prioridade\/download\/[^/]+$/,
];

/** Um path exige token? Mesma semântica do `app.use(AUTH_REQUIRED_PATHS, requireAuth)`. */
export function requiresAuth(pathname: string): boolean {
  return AUTH_REQUIRED_PATHS.some((entry) =>
    typeof entry === "string" ? pathname === entry || pathname.startsWith(`${entry}/`) : entry.test(pathname)
  );
}
